// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlotCreator.DAL;

#nullable disable

namespace PlotCreator.DAL.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlotCreator.Domain.Entity.Access_Modificator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Modificators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Публично"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Приватно"
                        });
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Book_cover")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("ModificatorId")
                        .HasColumnType("integer");

                    b.Property<int>("RatingId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("ModificatorId");

                    b.HasIndex("RatingId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Book_Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В процессе"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Завершен"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Заморожен"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Заброшен"
                        });
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Appearance")
                        .HasColumnType("text");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("Date");

                    b.Property<string>("Conflict")
                        .HasColumnType("text");

                    b.Property<DateTime>("Deathday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("Goals")
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("History")
                        .HasColumnType("text");

                    b.Property<string>("Motivation")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personality")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<int>("WorldviewId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorldviewId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Beginning")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<bool>("ChekhovsGun")
                        .HasColumnType("boolean");

                    b.Property<string>("Colour")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("Ending")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Мистика"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Драма"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Приключения"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ужасы"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Романтика"
                        });
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Parent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("Data_Creation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Book_Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CharacterId");

                    b.ToTable("Book-Character");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Book_Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("IdeaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("IdeaId");

                    b.ToTable("Book-Idea");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Episode_Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("Episode-Character");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Episode_Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("EventId");

                    b.ToTable("Episode-Event");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Event_Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EventId");

                    b.ToTable("Event-Character");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Group_Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("GroupId");

                    b.ToTable("Group-Character");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Group_Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("GroupId");

                    b.ToTable("Group-Event");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "0+"
                        },
                        new
                        {
                            Id = 2,
                            Name = "6+"
                        },
                        new
                        {
                            Id = 3,
                            Name = "12+"
                        },
                        new
                        {
                            Id = 4,
                            Name = "16+"
                        },
                        new
                        {
                            Id = 5,
                            Name = "18+"
                        });
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("roleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("roleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Worldview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Worldview");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "персонажи с таким мировоззрением считаются с правилами и совершают поступки, которых от них ожидает общество",
                            Name = "Законопослушно-доброе"
                        },
                        new
                        {
                            Id = 2,
                            Description = "персонажи с таким мировоззрением совершают хорошие поступки в соответствии со своими потребностями",
                            Name = "Нейтрально-доброе"
                        },
                        new
                        {
                            Id = 3,
                            Description = "персонажи с таким мировоззрением действуют по совести, с небольшой оглядкой на мнение и ожидания других",
                            Name = "Хаотично-доброе"
                        },
                        new
                        {
                            Id = 4,
                            Description = "персонажи с таким мировоззрением действуют в соответствии с законом, традицией, или своим кодексом",
                            Name = "Законопослушно-нейтральное"
                        },
                        new
                        {
                            Id = 5,
                            Description = "персонажи с таким мировоззрением предпочитают чистоту от моральных вопросов в своих действиях, и не принимают какой бы то ни было стороны, даже если одна из них более выгодна в данное время",
                            Name = "Хаотично-нейтральное"
                        },
                        new
                        {
                            Id = 6,
                            Description = "персонажи с таким мировоззрением следуют своим целям или капризам, вознося свою цель/свободу выше всего остального",
                            Name = "Нейтральное"
                        },
                        new
                        {
                            Id = 7,
                            Description = "персонажи с таким мировоззрением постоянно берут то, что хотят, в рамках традиции, лояльности или порядка",
                            Name = "Законопослушно-злое"
                        },
                        new
                        {
                            Id = 8,
                            Description = "персонажи с таким мировоззрением делают что угодно и когда угодно, без оглядки на сострадание и сомнение",
                            Name = "Нейтрально-злое"
                        },
                        new
                        {
                            Id = 9,
                            Description = "персонажи с таким мировоззрением совершают неконтролируемое насилие, стимулируемое их жадностью, ненавистью или жаждой крови",
                            Name = "Хаотично-злое"
                        });
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Book", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlotCreator.Domain.Entity.Access_Modificator", "Modificator")
                        .WithMany("Books")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlotCreator.Domain.Entity.Rating", "Rating")
                        .WithMany("Books")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlotCreator.Domain.Entity.Book_Status", "Status")
                        .WithMany("Books")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlotCreator.Domain.Entity.User", "User")
                        .WithMany("Books")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Modificator");

                    b.Navigation("Rating");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Character", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlotCreator.Domain.Entity.Worldview", "Worldview")
                        .WithMany("Characters")
                        .HasForeignKey("WorldviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Worldview");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Episode", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.Book", "Book")
                        .WithMany("Episodes")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Event", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.Book", "Book")
                        .WithMany("Events")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Group", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.Book", "Book")
                        .WithMany("Groups")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Idea", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.User", "User")
                        .WithMany("Ideas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Book_Character", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.Book", "Book")
                        .WithMany("Books_Characters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlotCreator.Domain.Entity.Character", "Character")
                        .WithMany("Books_Characters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Book_Idea", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.Book", "Book")
                        .WithMany("Books_Ideas")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlotCreator.Domain.Entity.Idea", "Idea")
                        .WithMany("Books_Ideas")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Episode_Character", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.Character", "Character")
                        .WithMany("Episodes_Characters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PlotCreator.Domain.Entity.Episode", "Episode")
                        .WithMany("Episodes_Characters")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Episode_Event", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.Episode", "Episode")
                        .WithMany("Episodes_Events")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PlotCreator.Domain.Entity.Event", "Event")
                        .WithMany("Episodes_Events")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Event_Character", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.Character", "Character")
                        .WithMany("Events_Characters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PlotCreator.Domain.Entity.Event", "Event")
                        .WithMany("Events_Characters")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Group_Character", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.Character", "Character")
                        .WithMany("Groups_Characters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PlotCreator.Domain.Entity.Group", "Group")
                        .WithMany("Groups_Characters")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Multiple_Tables.Group_Event", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.Event", "Event")
                        .WithMany("Groups_Events")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PlotCreator.Domain.Entity.Group", "Group")
                        .WithMany("Groups_Events")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.User", b =>
                {
                    b.HasOne("PlotCreator.Domain.Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Access_Modificator", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Book", b =>
                {
                    b.Navigation("Books_Characters");

                    b.Navigation("Books_Ideas");

                    b.Navigation("Episodes");

                    b.Navigation("Events");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Book_Status", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Character", b =>
                {
                    b.Navigation("Books_Characters");

                    b.Navigation("Episodes_Characters");

                    b.Navigation("Events_Characters");

                    b.Navigation("Groups_Characters");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Episode", b =>
                {
                    b.Navigation("Episodes_Characters");

                    b.Navigation("Episodes_Events");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Event", b =>
                {
                    b.Navigation("Episodes_Events");

                    b.Navigation("Events_Characters");

                    b.Navigation("Groups_Events");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Group", b =>
                {
                    b.Navigation("Groups_Characters");

                    b.Navigation("Groups_Events");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Idea", b =>
                {
                    b.Navigation("Books_Ideas");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Rating", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.User", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Characters");

                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("PlotCreator.Domain.Entity.Worldview", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
